title: Ankita Kumari Satapathy
#description: **ELECTRICAL AND ELECTRONICS ENGINEERING STUDENT at NIST UNIVERSITY**
#show_downloads: true
linkedin: linkedin.com/in/ankita-kumari-satapathy-583bb932a
theme: jekyll-theme-time-machine
