title: Ankita Kumari Satapathy
description: **ELECTRICAL AND ELECTRONICS ENGINEERING STUDENT @NIST UNIVERSITY|| Ex-Intern at MSME Tool Room Bhubaneswar (Government of India) || MATLAB || PYTHON || VERILOG || VHDL || C Language || MySQL**
#show_downloads: true
theme: jekyll-theme-minimal
