title: Ankita Kumari Satapathy
#description: **ELECTRICAL AND ELECTRONICS ENGINEERING STUDENT at NIST UNIVERSITY**
#show_downloads: true
linkedin: https://www.linkedin.com/in/ankita-kumari-satapathy-583bb932a?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BvRZOI4k3QUCXtZ3OLq5Ueg%3D%3D
mail id: ankitasatapathy23@gmail.com
theme: jekyll-theme-minimal
